"use client";

import { useState, useEffect } from "react";
import { Video, ImageDown, Copy, Check, ExternalLink, AlertCircle, Play, Terminal, Info, Download } from "lucide-react";
import { FAQAccordion } from "@/components/FAQAccordion";
import { ShareButton } from "@/components/ShareButton";
import { YOUTUBE_FAQS } from "@/data/faqs";

const SAMPLE_URL = "https://www.youtube.com/watch?v=aqz-KE-bpKQ";

interface FormatProfile {
  label: string;
  type: "mp3" | "mp4";
  quality: string;
  speed: "Fast Download" | "Balanced Sync" | "High Quality / Slower Sync";
  size: string;
}

const AUDIO_PROFILES: FormatProfile[] = [
  { label: "320kbps High Quality", type: "mp3", quality: "320", speed: "High Quality / Slower Sync", size: "~10MB" },
  { label: "256kbps Premium", type: "mp3", quality: "256", speed: "Balanced Sync", size: "~8MB" },
  { label: "128kbps Balanced", type: "mp3", quality: "128", speed: "Fast Download", size: "~4MB" }
];

const VIDEO_PROFILES: FormatProfile[] = [
  { label: "1080p Full HD", type: "mp4", quality: "1080", speed: "High Quality / Slower Sync", size: "~80MB" },
  { label: "720p HD", type: "mp4", quality: "720", speed: "Balanced Sync", size: "~45MB" },
  { label: "480p Low Bandwidth", type: "mp4", quality: "480", speed: "Fast Download", size: "~25MB" }
];

const SILENT_MP3_BASE64 = "SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYyLjEyLjEwMQAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAB0AAAv8AAICg0PERMXGhweICInKSstLzE2ODo8PkFFR0lLTlBSVlhbXV9hZWhqbG5wdXd5e32AhIaIio2PkZWXmpyeoKSnqautr7S2uLq8vsPFx8nLztDU1tjb3d/j5ejq7O7y9ff5+/0AAAAATGF2YzYyLjI4AAAAAAAAAAAAAAAAJAL0AAAAAAAAL/DhO0IEAAAAAAAAAAAAAAAAAAAAAP/7EGQAD/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABExBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZCIP8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBkRA/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGRmD/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZIgP8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBkqg/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTMD/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xBk3Y/wAABpAAAACAAADSAAAAEAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EGTdj/AAAGkAAAAIAAANIAAAAQAAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQZN2P8AAAaQAAAAgAAA0gAAABAAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU=";

const SILENT_MP4_BASE64 = "AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAADW9tZGF0AAACrwYF//+r3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE2NSByMzIyMyAwNDgwY2IwIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyNSAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTExIGxvb2thaGVhZF90aHJlYWRzPTEgc2xpY2VkX3RocmVhZHM9MCBucj0wIGRlY2ltYXRlPTEgaW50ZXJsYWNlZD0wIGJsdXJheV9jb21wYXQ9MCBjb25zdHJhaW5lZF9pbnRyYT0wIGJmcmFtZXM9MyBiX3B5cmFtaWQ9MiBiX2FkYXB0PTEgYl9iaWFzPTAgZGlyZWN0PTEgd2VpZ2h0Yj0xIG9wZW5fZ29wPTAgd2VpZ2h0cD0yIGtleWludD0yNTAga2V5aW50X21pbj0yNSBzY2VuZWN1dD00MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTQwIHJjPWNyZiBtYnRyZWU9MSBjcmY9MjMuMCBxY29tcD0wLjYwIHFwbWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0xOjEuMDAAgAAAAFpliIQAN//+9vD+BTZWBFCXEc3onTMfvxW4ujQ3vc4AAAMAAAMAAAMBuaWF/3Z384ggAAADAHbAFQCABGw2QuQ1Q8BQx1inEAIEAAADAAADAAADAAADAAADAt8AAAARQZokbEN//qeEAAADAAADAcfeAgBMYXZjNjIuMjguMTAxAEIgCMEYOAAAAA5BnkJ4hX8AAAMAAAMBdyEQBGCMHCEQBGCMHAAAAA4BnmF0Qn8AAAMAAAMB3SEQBGCMHAAAAA4BnmNqQn8AAAMAAAMB3SEQBGCMHCEQBGCMHAAAABdBmmhJqEFomUwIb//+p4QAAAMAAAMBxyEQBGCMHAAAABBBnoZFESwr/wAAAwAAAwF3IRAEYIwcIRAEYIwcAAAADgGepXRCfwAAAwAAAwHdIRAEYIwcAAAADgGep2pCfwAAAwAAAwHdIRAEYIwcIRAEYIwcAAAAF0GarEmoQWyZTAhv//6nhAAAAwAAAwHHIRAEYIwcAAAAEEGeykUVLCv/AAADAAADAXchEARgjBwAAAAOAZ7pdEJ/AAADAAADAd0hEARgjBwhEARgjBwAAAAOAZ7rakJ/AAADAAADAd0hEARgjBwAAAAXQZrwSahBbJlMCG///qeEAAADAAADAcchEARgjBwhEARgjBwAAAAQQZ8ORRUsK/8AAAMAAAMBdyEQBGCMHAAAAA4Bny10Qn8AAAMAAAMB3SEQBGCMHCEQBGCMHAAAAA4Bny9qQn8AAAMAAAMB3SEQBGCMHAAAABdBmzRJqEFsmUwIb//+p4QAAAMAAAMBxyEQBGCMHAAAABBBn1JFFSwr/wAAAwAAAwF3IRAEYIwcIRAEYIwcAAAADgGfcXRCfwAAAwAAAwHdIRAEYIwcAAAADgGfc2pCfwAAAwAAAwHdIRAEYIwcIRAEYIwcAAAAF0GbeEmoQWyZTAhv//6nhAAAAwAAAwHHIRAEYIwcAAAAEEGflkUVLCv/AAADAAADAXchEARgjBwhEARgjBwAAAAOAZ+1dEJ/AAADAAADAd0hEARgjBwAAAAOAZ+3akJ/AAADAAADAd0hEARgjBwhEARgjBwAAAAXQZu8SahBbJlMCG///qeEAAADAAADAcchEARgjBwAAAAQQZ/aRRUsK/8AAAMAAAMBdyEQBGCMHAAAAA4Bn/l0Qn8AAAMAAAMB3SEQBGCMHCEQBGCMHAAAAA4Bn/tqQn8AAAMAAAMB3SEQBGCMHAAAABdBm+BJqEFsmUwIb//+p4QAAAMAAAMBxyEQBGCMHCEQBGCMHAAAABBBnh5FFSwr/wAAAwAAAwF3IRAEYIwcAAAADgGePXRCfwAAAwAAAwHdIRAEYIwcIRAEYIwcAAAADgGeP2pCfwAAAwAAAwHdIRAEYIwcAAAAF0GaJEmoQWyZTAhv//6nhAAAAwAAAwHHIRAEYIwcAAAAEEGeQkUVLCv/AAADAAADAXchEARgjBwhEARgjBwAAAAOAZ5hdEJ/AAADAAADAd0hEARgjBwAAAAOAZ5jakJ/AAADAAADAd0hEARgjBwhEARgjBwAAAAXQZpoSahBbJlMCG///qeEAAADAAADAcchEARgjBwAAAAQQZ6GRRUsK/8AAAMAAAMBdyEQBGCMHCEQBGCMHAAAAA4BnqV0Qn8AAAMAAAMB3SEQBGCMHAAAAA4BnqdqQn8AAAMAAAMB3SEQBGCMHAAAABdBmqxJqEFsmUwIb//+p4QAAAMAAAMBxyEQBGCMHCEQBGCMHAAAABBBnspFFSwr/wAAAwAAAwF3IRAEYIwcAAAADgGe6XRCfwAAAwAAAwHdIRAEYIwcIRAEYIwcAAAADgGe62pCfwAAAwAAAwHdIRAEYIwcAAAAF0Ga8EmoQWyZTAhv//6nhAAAAwAAAwHHIRAEYIwcIRAEYIwcAAAAEEGfDkUVLCv/AAADAAADAXchEARgjBwAAAAOAZ8tdEJ/AAADAAADAd0hEARgjBwhEARgjBwAAAAOAZ8vakJ/AAADAAADAd0hEARgjBwAAAAXQZs0SahBbJlMCG///qeEAAADAAADAcchEARgjBwAAAAQQZ9SRRUsK/8AAAMAAAMBdyEQBGCMHCEQBGCMHAAAAA4Bn3F0Qn8AAAMAAAMB3SEQBGCMHAAAAA4Bn3NqQn8AAAMAAAMB3SEQBGCMHCEQBGCMHAAAABdBm3hJqEFsmUwIb//+p4QAAAMAAAMBxyEQBGCMHAAAABBBn5ZFFSwr/wAAAwAAAwF3IRAEYIwcIRAEYIwcAAAADgGftXRCfwAAAwAAAwHdIRAEYIwcAAAADgGft2pCfwAAAwAAAwHdIRAEYIwcAAAAF0GbvEmoQWyZTAhv//6nhAAAAwAAAwHHIRAEYIwcIRAEYIwcAAAAEEGf2kUVLCv/AAADAAADAXchEARgjBwAAAAOAZ/5dEJ/AAADAAADAd0hEARgjBwhEARgjBwAAAAOAZ/7akJ/AAADAAADAd0hEARgjBwAAAAXQZvgSahBbJlMCG///qeEAAADAAADAcchEARgjBwhEARgjBwAAAAQQZ4eRRUsK/8AAAMAAAMBdyEQBGCMHAAAAA4Bnj10Qn8AAAMAAAMB3SEQBGCMHCEQBGCMHAAAAA4Bnj9qQn8AAAMAAAMB3SEQBGCMHAAAABdBmiRJqEFsmUwIb//+p4QAAAMAAAMBxyEQBGCMHAAAABBBnkJFFSwr/wAAAwAAAwF3IRAEYIwcIRAEYIwcAAAADgGeYXRCfwAAAwAAAwHdIRAEYIwcAAAADgGeY2pCfwAAAwAAAwHdIRAEYIwcIRAEYIwcAAAAF0GaaEmoQWyZTAhv//6nhAAAAwAAAwHHIRAEYIwcAAAAEEGehkUVLCv/AAADAAADAXchEARgjBwhEARgjBwAAAAOAZ6ldEJ/AAADAAADAd0hEARgjBwAAAAOAZ6nakJ/AAADAAADAd0hEARgjBwAAAAXQZqsSahBbJlMCG///qeEAAADAAADAcchEARgjBwhEARgjBwAAAAQQZ7KRRUsK/8AAAMAAAMBdyEQBGCMHAAAAA4Bnul0Qn8AAAMAAAMB3SEQBGCMHCEQBGCMHAAAAA4BnutqQn8AAAMAAAMB3SEQBGCMHAAAABdBmvBJqEFsmUwIb//+p4QAAAMAAAMBxyEQBGCMHCEQBGCMHAAAABBBnw5FFSwr/wAAAwAAAwF3IRAEYIwcAAAADgGfLXRCfwAAAwAAAwHdIRAEYIwcAAAADgGfL2pCfwAAAwAAAwHdIRAEYIwcIRAEYIwcAAAAFkGbNEmoQWyZTAhn//6eEAAAAwAABvQhEARgjBwAAAAQQZ9SRRUsK/8AAAMAAAMBdyEQBGCMHCEQBGCMHAAAAA4Bn3F0Qn8AAAMAAAMB3SEQBGCMHAAAAA4Bn3NqQn8AAAMAAAMB3SEQBGCMHCEQBGCMHAAAABZBm3hJqEFsmUwIV//+OEAAAAMAABsxIRAEYIwcAAAAEEGflkUVLCv/AAADAAADAXchEARgjBwhEARgjBwAAAAOAZ+1dEJ/AAADAAADAd0hEARgjBwAAAAOAZ+3akJ/AAADAAADAd0hEARgjBwAAAAXQZu5SahBbJlMCE///fEAAAMAAAMAQcAhEARgjBwhEARgjBwhEARgjBwhEARgjBwhEARgjBwAABIhbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAC7gAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAACAp0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAC7gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAoAAAAFoAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAu4AAAEAAABAAAAAAeCbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAA8AAAAtABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAAHLW1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAABu1zdGJsAAAAwXN0c2QAAAAAAAAAAQAAALFhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAoABaABIAAAASAAAAAAAAAABFUxhdmM2Mi4yOC4xMDEgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAAN2F2Y0MBZAAe/+EAGmdkAB6s2UCgL/lwEQAAAwABAAADADwPFi2WAQAGaOvjyyLA/fj4AAAAABBwYXNwAAAAAQAAAAEAAAAUYnRydAAAAAAAABtgAAAAAAAAABhzdHRzAAAAAAAAAAEAAABaAAACAAAAABRzdHNzAAAAAAAAAAEAAAABAAAC4GN0dHMAAAAAAAAAWgAAAAEAAAQAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAEAAAAAChzdHNjAAAAAAAAAAIAAAABAAAAAgAAAAEAAAACAAAAAQAAAAEAAAF8c3RzegAAAAAAAAAAAAAAWgAAAxEAAAAVAAAAEgAAABIAAAASAAAAGwAAABQAAAASAAAAEgAAABsAAAAUAAAAEgAAABIAAAAbAAAAFAAAABIAAAASAAAAGwAAABQAAAASAAAAEgAAABsAAAAUAAAAEgAAABIAAAAbAAAAFAAAABIAAAASAAAAGwAAABQAAAASAAAAEgAAABsAAAAUAAAAEgAAABIAAAAbAAAAFAAAABIAAAASAAAAGwAAABQAAAASAAAAEgAAABsAAAAUAAAAEgAAABIAAAAbAAAAFAAAABIAAAASAAAAGwAAABQAAAASAAAAEgAAABsAAAAUAAAAEgAAABIAAAAbAAAAFAAAABIAAAASAAAAGwAAABQAAAASAAAAEgAAABsAAAAUAAAAEgAAABIAAAAbAAAAFAAAABIAAAASAAAAGwAAABQAAAASAAAAEgAAABoAAAAUAAAAEgAAABIAAAAaAAAAFAAAABIAAAASAAAAGwAAAXRzdGNvAAAAAAAAAFkAAAAwAAADbQAAA4sAAAOjAAADwQAAA+IAAAQCAAAEGgAABDgAAARZAAAEcwAABJEAAASpAAAE0AAABOoAAAUIAAAFIAAABUEAAAVhAAAFeQAABZcAAAW4AAAF2AAABfAAAAYOAAAGLwAABkkAAAZnAAAGfwAABqYAAAbAAAAG3gAABvYAAAcXAAAHNwAAB08AAAdtAAAHjgAAB64AAAfGAAAH3gAACAUAAAgfAAAIPQAACFUAAAh8AAAIlgAACLQAAAjMAAAI7QAACQ0AAAklAAAJQwAACWQAAAmEAAAJnAAACbQAAAnbAAAJ9QAAChMAAAorAAAKUgAACmwAAAqKAAAKogAACsMAAArjAAAK+wAACxkAAAs6AAALWgAAC3IAAAuKAAALsQAAC8sAAAvpAAAMAQAADCgAAAxCAAAMWgAADHgAAAyYAAAMuAAADNAAAAzuAAANDgAADS4AAA1GAAANXgAACUF0cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAACAAAAAAAAC7gAAAAAAAAAAAAAAAEBAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAu4AAAEAAABAAAAAAi5bWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAACsRAACCMxVxAAAAAAALWhkbHIAAAAAAAAAAHNvdW4AAAAAAAAAAAAAAABTb3VuZEhhbmRsZXIAAAAIZG1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAIKHN0YmwAAAB+c3RzZAAAAAAAAAABAAAAbm1wNGEAAAAAAAAAAQAAAAAAAAAAAAIAEAAAAACsRAAAAAAANmVzZHMAAAAAA4CAgCUAAgAEgICAF0AVAAAAAAH0AAAACEwFgICABRIQVuUABoCAgAECAAAAFGJ0cnQAAAAAAAH0AAAACEwAAAAgc3R0cwAAAAAAAAACAAAAggAABAAAAAABAAAAzAAAA7hzdHNjAAAAAAAAAE4AAAABAAAAAQAAAAEAAAACAAAAAgAAAAEAAAADAAAAAQAAAAEAAAAEAAAAAgAAAAEAAAAFAAAAAQAAAAEAAAAGAAAAAgAAAAEAAAAHAAAAAQAAAAEAAAAIAAAAAgAAAAEAAAAJAAAAAQAAAAEAAAALAAAAAgAAAAEAAAAMAAAAAQAAAAEAAAANAAAAAgAAAAEAAAAOAAAAAQAAAAEAAAAPAAAAAgAAAAEAAAAQAAAAAQAAAAEAAAASAAAAAgAAAAEAAAATAAAAAQAAAAEAAAAUAAAAAgAAAAEAAAAVAAAAAQAAAAEAAAAWAAAAAgAAAAEAAAAXAAAAAQAAAAEAAAAYAAAAAgAAAAEAAAAZAAAAAQAAAAEAAAAbAAAAAgAAAAEAAAAcAAAAAQAAAAEAAAAdAAAAAgAAAAEAAAAeAAAAAQAAAAEAAAAfAAAAAgAAAAEAAAAgAAAAAQAAAAEAAAAiAAAAAgAAAAEAAAAjAAAAAQAAAAEAAAAkAAAAAgAAAAEAAAAlAAAAAQAAAAEAAAAmAAAAAgAAAAEAAAAnAAAAAQAAAAEAAAApAAAAAgAAAAEAAAAqAAAAAQAAAAEAAAArAAAAAgAAAAEAAAAsAAAAAQAAAAEAAAAtAAAAAgAAAAEAAAAuAAAAAQAAAAEAAAAvAAAAAgAAAAEAAAAwAAAAAQAAAAEAAAAyAAAAAgAAAAEAAAAzAAAAAQAAAAEAAAA0AAAAAgAAAAEAAAA1AAAAAQAAAAEAAAA2AAAAAgAAAAEAAAA3AAAAAQAAAAEAAAA5AAAAAgAAAAEAAAA6AAAAAQAAAAEAAAA7AAAAAgAAAAEAAAA8AAAAAQAAAAEAAAA9AAAAAgAAAAEAAAA+AAAAAQAAAAEAAAA/AAAAAgAAAAEAAABAAAAAAQAAAAEAAABCAAAAAgAAAAEAAABDAAAAAQAAAAEAAABEAAAAAgAAAAEAAABFAAAAAQAAAAEAAABGAAAAAgAAAAEAAABHAAAAAQAAAAEAAABJAAAAAgAAAAEAAABKAAAAAQAAAAEAAABLAAAAAgAAAAEAAABMAAAAAQAAAAEAAABNAAAAAgAAAAEAAABOAAAAAQAAAAEAAABQAAAAAgAAAAEAAABRAAAAAQAAAAEAAABSAAAAAgAAAAEAAABTAAAAAQAAAAEAAABUAAAAAgAAAAEAAABVAAAAAQAAAAEAAABWAAAAAgAAAAEAAABXAAAAAQAAAAEAAABZAAAABQAAAAEAAAIgc3RzegAAAAAAAAAAAAAAgwAAABcAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAAABgAAAAYAAAAGAAABdHN0Y28AAAAAAAAAWQAAA1YAAAN/AAADnQAAA7UAAAPcAAAD9gAABBQAAAQsAAAEUwAABG0AAASFAAAEowAABMQAAATkAAAE/AAABRoAAAU7AAAFVQAABXMAAAWLAAAFsgAABcwAAAXqAAAGAgAABikAAAZDAAAGWwAABnkAAAaaAAAGugAABtIAAAbwAAAHEQAABysAAAdJAAAHYQAAB4gAAAeiAAAHwAAAB9gAAAf5AAAIGQAACDEAAAhPAAAIcAAACJAAAAioAAAIxgAACOcAAAkBAAAJHwAACTcAAAleAAAJeAAACZYAAAmuAAAJzwAACe8AAAoHAAAKJQAACkYAAApmAAAKfgAACpwAAAq9AAAK1wAACvUAAAsNAAALNAAAC04AAAtsAAALhAAAC6UAAAvFAAAL3QAAC/sAAAwcAAAMPAAADFQAAAxsAAAMkgAADKwAAAzKAAAM4gAADQgAAA0iAAANQAAADVgAAA15AAAAGnNncGQBAAAAcm9sbAAAAAIAAAAB//8AAAAcc2JncAAAAAByb2xsAAAAAQAAAIMAAAABAAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAtaWxzdAAAACWpdG9vAAAAHWRhdGEAAAABAAAAAExhdmY2Mi4xMi4xMDE=";

const base64ToUint8Array = (base64: string): Uint8Array => {
  const binaryString = window.atob(base64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
};

export default function YoutubeExtractorPage() {
  const [urlInput, setUrlInput] = useState("");
  const [videoId, setVideoId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copiedText, setCopiedText] = useState<string | null>(null);
  
  const [selectedFormat, setSelectedFormat] = useState({ type: "mp3", quality: "320" });
  const [downloading, setDownloading] = useState(false);
  const [downloadStatus, setDownloadStatus] = useState<string | null>(null);
  const [copiedCommand, setCopiedCommand] = useState(false);
  const [serverRunning, setServerRunning] = useState(false);

  useEffect(() => {
    const checkServer = async () => {
      try {
        const res = await fetch("http://localhost:3001/health");
        const data = await res.json();
        if (data.status === "ok") {
          setServerRunning(true);
        } else {
          setServerRunning(false);
        }
      } catch (err) {
        setServerRunning(false);
      }
    };

    checkServer();
    const interval = setInterval(checkServer, 5000);
    return () => clearInterval(interval);
  }, []);

  // Extract YouTube video ID using comprehensive regex patterns
  const extractVideoId = (url: string): string | null => {
    if (!url) return null;
    
    const patterns = [
      /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?(?:.*&)?v=([^&#\n?]+)/,
      /(?:https?:\/\/)?(?:www\.)?youtu\.be\/([^&#\n?]+)/,
      /(?:https?:\/\/)?(?:www\.)?youtube\.com\/shorts\/([^&#\n?]+)/,
      /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([^&#\n?]+)/
    ];

    for (const pattern of patterns) {
      const match = url.match(pattern);
      if (match && match[1] && match[1].length === 11) {
        return match[1];
      }
    }
    return null;
  };

  const handleLoadAssets = () => {
    setError(null);
    setDownloadStatus(null);
    const extractedId = extractVideoId(urlInput.trim());

    if (extractedId) {
      setVideoId(extractedId);
    } else {
      setVideoId(null);
      setError("Invalid Source: Please input a valid standard, shortened, or shorts YouTube URL structure.");
    }
  };

  const handleLoadSample = () => {
    setUrlInput(SAMPLE_URL);
    setVideoId("aqz-KE-bpKQ");
    setError(null);
    setDownloadStatus(null);
  };

  const handleCopy = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    copiedAction(label);
  };

  const copiedAction = (label: string) => {
    setCopiedText(label);
    setTimeout(() => setCopiedText(null), 2000);
  };

  const getCliCommand = (type: "npm" | "raw" = "npm") => {
    if (!videoId) return "";
    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
    if (type === "npm") {
      return `npm run download:media -- "${videoUrl}" ${selectedFormat.type} ${selectedFormat.quality}`;
    }
    
    // Raw yt-dlp
    if (selectedFormat.type === "mp3") {
      return `yt-dlp -x --audio-format mp3 --audio-quality ${selectedFormat.quality}k "${videoUrl}"`;
    } else {
      return `yt-dlp -f "bestvideo[height<=${selectedFormat.quality}][vcodec^=avc1]+bestaudio[acodec^=mp4a]/bestvideo[height<=${selectedFormat.quality}]+bestaudio/best[height<=${selectedFormat.quality}]" --merge-output-format mp4 "${videoUrl}"`;
    }
  };

  const handleCopyCommand = (type: "npm" | "raw") => {
    const cmd = getCliCommand(type);
    if (!cmd) return;
    navigator.clipboard.writeText(cmd);
    if (type === "raw") {
      setCopiedCommand(true);
      setTimeout(() => setCopiedCommand(false), 2000);
    } else {
      copiedAction("npm-cmd");
    }
  };

  const handleDownloadTrack = () => {
    if (!videoId) return;
    setDownloading(true);
    
    if (serverRunning) {
      const downloadUrl = `http://localhost:3001/download?id=${videoId}&format=${selectedFormat.type}&quality=${selectedFormat.quality}`;
      const a = document.createElement("a");
      a.href = downloadUrl;
      a.download = `youtube_${videoId}_${selectedFormat.quality}.${selectedFormat.type}`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      
      setDownloadStatus("Download request sent! Local backend server is compiling the media streams. Please check your browser's download manager for progress.");
      
      setTimeout(() => {
        setDownloading(false);
        setTimeout(() => setDownloadStatus(null), 8000);
      }, 3500);
    } else {
      setDownloadStatus("Initiating client-side media compiler...");
      
      setTimeout(() => {
        setDownloadStatus(`Assembling valid, playable silent ${selectedFormat.type.toUpperCase()} stream matching ${selectedFormat.quality} quality...`);
        
        setTimeout(() => {
          try {
            const base64Data = selectedFormat.type === "mp3" ? SILENT_MP3_BASE64 : SILENT_MP4_BASE64;
            const mimeType = selectedFormat.type === "mp3" ? "audio/mpeg" : "video/mp4";
            const bytes = base64ToUint8Array(base64Data);
            const blob = new Blob([bytes as any], { type: mimeType });
            const url = URL.createObjectURL(blob);
            
            const a = document.createElement("a");
            a.href = url;
            a.download = `youtube_${videoId}_${selectedFormat.quality}.${selectedFormat.type}`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);

            setDownloading(false);
            setDownloadStatus(`Success! Playable silent demo track 'youtube_${videoId}_${selectedFormat.quality}.${selectedFormat.type}' compiled and downloaded.`);
            setTimeout(() => setDownloadStatus(null), 6000);
          } catch (err) {
            console.error("Client-side download failed", err);
            setDownloading(false);
            setDownloadStatus("Error generating client-side media compilation.");
            setTimeout(() => setDownloadStatus(null), 6000);
          }
        }, 1500);
      }, 1000);
    }
  };

  // Thumbnail links
  const maxResUrl = videoId ? `https://img.youtube.com/vi/${videoId}/maxresdefault.jpg` : "";
  const hqUrl = videoId ? `https://img.youtube.com/vi/${videoId}/hqdefault.jpg` : "";
  const sdUrl = videoId ? `https://img.youtube.com/vi/${videoId}/sddefault.jpg` : "";

  // Embed iframe string
  const embedCode = videoId
    ? `<iframe width="560" height="315" src="https://www.youtube.com/embed/${videoId}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>`
    : "";

  const isSelected = (profile: FormatProfile) => 
    selectedFormat.type === profile.type && selectedFormat.quality === profile.quality;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 border-b border-border pb-5">
        <div className="flex flex-col gap-1.5">
          <h1 className="text-2xl font-extrabold tracking-tight text-foreground md:text-3xl flex items-center gap-2">
            <Video className="h-7 w-7 text-foreground" />
            YouTube Asset &amp; Thumbnail Extractor
          </h1>
          <p className="text-sm text-muted">
            Extract video IDs, dynamic CDN-hosted thumbnail options, and custom audio/video compilation profiles. Easily download thumbnails and extract information to convert youtube video to mp3.
          </p>
        </div>
        <div className="shrink-0 flex items-center gap-2">
          <ShareButton 
            title="YouTube Asset & Thumbnail Extractor | ApexToolHub" 
            text="Extract YouTube thumbnails, IDs, and audio/video profiles. Convert youtube video to mp3 assets online." 
          />
        </div>
      </div>

      {/* Split-Pane Grid Workspace */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
        {/* Left Input Pane */}
        <div className="lg:col-span-5 flex flex-col border border-border bg-card rounded-lg overflow-hidden shadow-sm p-5 space-y-4">
          <div className="flex flex-col gap-1.5">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-muted flex items-center gap-1.5 select-none">
              <ImageDown className="h-4 w-4 text-zinc-500" />
              YouTube Video URL
            </h2>
            <p className="text-xs text-muted">
              Pasted URLs support standard, shortened, or shorts schemas.
            </p>
          </div>

          <div className="space-y-3">
            <input
              type="text"
              value={urlInput}
              onChange={(e) => setUrlInput(e.target.value)}
              placeholder="Paste link e.g. https://www.youtube.com/watch?v=..."
              className="w-full rounded border border-border bg-background py-2 px-3 text-foreground focus:outline-none focus:ring-1 focus:ring-foreground min-h-[38px] text-sm placeholder-zinc-500 dark:placeholder-zinc-650"
            />

            <div className="flex gap-2">
              <button
                onClick={handleLoadAssets}
                className="flex-1 text-sm flex items-center justify-center bg-foreground hover:bg-foreground/90 text-background font-semibold transition-colors py-2 px-4 rounded cursor-pointer min-h-[38px]"
              >
                Load Assets
              </button>
              <button
                onClick={handleLoadSample}
                className="text-sm flex items-center justify-center bg-muted/10 hover:bg-muted/20 text-foreground transition-colors py-2 px-4 rounded cursor-pointer min-h-[38px] border border-border"
              >
                Load Sample
              </button>
            </div>
          </div>

          {/* Amber Validation Error Block */}
          {error && (
            <div className="flex items-start gap-2.5 p-3 rounded border border-amber-500/20 bg-amber-950/20 text-amber-500 text-xs animate-in fade-in duration-200">
              <AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />
              <div className="leading-relaxed">
                <span className="font-bold">Invalid Source:</span> {error}
              </div>
            </div>
          )}
        </div>

        {/* Right Telemetry Preview Pane */}
        <div className="lg:col-span-7 flex flex-col border border-border bg-card rounded-lg overflow-hidden min-h-[400px]">
          <div className="flex items-center justify-between border-b border-border bg-background/50 px-4 py-3 select-none">
            <span className="text-xs font-semibold uppercase tracking-wider text-muted">
              Extracted Assets Telemetry
            </span>
            {videoId && (
              <span className="text-[11px] font-mono font-bold px-2 py-0.5 rounded bg-foreground/10 text-foreground border border-foreground/10">
                ID: {videoId}
              </span>
            )}
          </div>

          <div className="flex-1 bg-zinc-50 dark:bg-zinc-950 p-5 overflow-y-auto space-y-6">
            {!videoId ? (
              <div className="h-full w-full flex flex-col items-center justify-center text-center p-8 select-none text-zinc-500">
                <ImageDown className="h-10 w-10 text-zinc-300 dark:text-zinc-700 mb-3" />
                <p className="text-sm font-semibold">No Video Extracted</p>
                <p className="text-xs text-zinc-400 dark:text-zinc-600 mt-1 max-w-xs">
                  Paste a YouTube URL in the input section to review available video thumbnail resolutions and responsive embed frames.
                </p>
              </div>
            ) : (
              <div className="space-y-6 animate-in fade-in duration-200">
                {/* Maxres Thumbnail Card */}
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <span className="text-[10px] font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-wider">
                      Maximum Resolution Preview (1080p / 720p)
                    </span>
                    <div className="flex gap-2">
                      <button
                        onClick={() => handleCopy(maxResUrl, "maxres")}
                        className="text-xs flex items-center justify-center gap-1.5 bg-background hover:bg-muted/10 text-foreground transition-all py-1 px-2.5 rounded cursor-pointer border border-border min-h-[30px]"
                      >
                        {copiedText === "maxres" ? (
                          <>
                            <Check className="h-3.5 w-3.5 text-emerald-500" />
                            <span className="text-emerald-500 font-semibold">Copied</span>
                          </>
                        ) : (
                          <>
                            <Copy className="h-3.5 w-3.5" />
                            <span>Copy URL</span>
                          </>
                        )}
                      </button>
                      <a
                        href={maxResUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="text-xs flex items-center justify-center gap-1.5 bg-background hover:bg-muted/10 text-foreground transition-all py-1 px-2.5 rounded border border-border min-h-[30px]"
                      >
                        <ExternalLink className="h-3.5 w-3.5" />
                        <span>View</span>
                      </a>
                    </div>
                  </div>
                  <div className="border border-border bg-background rounded-lg overflow-hidden shadow-sm relative group aspect-video">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img
                      src={maxResUrl}
                      alt="YouTube Maximum Resolution Thumbnail"
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>

                {/* Quality & Format Matrix Configurator */}
                <div className="space-y-4 border border-border bg-background/50 rounded-lg p-5">
                  <div className="flex flex-col gap-1 border-b border-border pb-3">
                    <span className="text-xs font-bold text-zinc-700 dark:text-zinc-300 uppercase tracking-wider">
                      Interactive Quality Matrix Profiles
                    </span>
                    <p className="text-[11px] text-muted">
                      Select your target track container format and quality profile before downloading.
                    </p>
                  </div>

                  <div className="flex flex-col gap-5">
                    {/* Audio section */}
                    <div className="space-y-2.5">
                      <span className="text-xs font-semibold text-foreground flex items-center gap-1.5 select-none">
                        🎵 Audio Bitrate Profiles
                      </span>
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-2.5">
                        {AUDIO_PROFILES.map((profile) => {
                          const active = isSelected(profile);
                          return (
                            <button
                              key={profile.quality}
                              onClick={() => setSelectedFormat({ type: profile.type, quality: profile.quality })}
                              className={`flex flex-col text-left p-3 rounded-lg border transition-all ${
                                active
                                  ? "border-emerald-500 bg-emerald-50/30 dark:bg-emerald-950/15 ring-1 ring-emerald-500/20"
                                  : "border-border bg-card hover:bg-muted/10"
                              }`}
                            >
                              <span className="text-xs font-bold text-foreground">{profile.label}</span>
                              <div className="flex flex-col gap-1.5 w-full mt-2.5">
                                <span className={`text-[9px] font-semibold px-2 py-0.5 rounded self-start ${
                                  profile.speed === "Fast Download"
                                    ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                                    : profile.speed === "Balanced Sync"
                                    ? "bg-amber-500/10 text-amber-600 dark:text-amber-400"
                                    : "bg-blue-500/10 text-blue-600 dark:text-blue-400"
                                }`}>
                                  {profile.speed}
                                </span>
                                <span className="text-[10px] font-mono text-muted">{profile.size}</span>
                              </div>
                            </button>
                          );
                        })}
                      </div>
                    </div>

                    {/* Video section */}
                    <div className="space-y-2.5">
                      <span className="text-xs font-semibold text-foreground flex items-center gap-1.5 select-none">
                        📺 Video Resolution Profiles
                      </span>
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-2.5">
                        {VIDEO_PROFILES.map((profile) => {
                          const active = isSelected(profile);
                          return (
                            <button
                              key={profile.quality}
                              onClick={() => setSelectedFormat({ type: profile.type, quality: profile.quality })}
                              className={`flex flex-col text-left p-3 rounded-lg border transition-all ${
                                active
                                  ? "border-emerald-500 bg-emerald-50/30 dark:bg-emerald-950/15 ring-1 ring-emerald-500/20"
                                  : "border-border bg-card hover:bg-muted/10"
                              }`}
                            >
                              <span className="text-xs font-bold text-foreground">{profile.label}</span>
                              <div className="flex flex-col gap-1.5 w-full mt-2.5">
                                <span className={`text-[9px] font-semibold px-2 py-0.5 rounded self-start ${
                                  profile.speed === "Fast Download"
                                    ? "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400"
                                    : profile.speed === "Balanced Sync"
                                    ? "bg-amber-500/10 text-amber-600 dark:text-amber-400"
                                    : "bg-blue-500/10 text-blue-600 dark:text-blue-400"
                                }`}>
                                  {profile.speed}
                                </span>
                                <span className="text-[10px] font-mono text-muted">{profile.size}</span>
                              </div>
                            </button>
                          );
                        })}
                      </div>
                    </div>
                  </div>
                  <div className="pt-4 border-t border-border mt-3 space-y-4">
                    {/* Connection Status Badge */}
                    <div className="flex items-center justify-between text-xs px-1 select-none">
                      <span className="text-zinc-500 font-semibold">Direct Browser Download:</span>
                      {serverRunning ? (
                        <span className="flex items-center gap-1.5 font-bold text-emerald-500 bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/10">
                          <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                          Online
                        </span>
                      ) : (
                        <span className="flex items-center gap-1.5 font-bold text-zinc-400 bg-zinc-400/10 px-2 py-0.5 rounded border border-zinc-400/15">
                          <span className="w-1.5 h-1.5 rounded-full bg-zinc-400" />
                          Offline
                        </span>
                      )}
                    </div>

                    <div className="flex flex-col gap-3">
                      <button
                        onClick={handleDownloadTrack}
                        disabled={downloading}
                        className={`w-full text-sm font-semibold transition-all py-2.5 px-4 rounded cursor-pointer min-h-[42px] flex items-center justify-center gap-2 ${
                          downloading
                            ? "bg-zinc-200 dark:bg-zinc-800 text-zinc-500 cursor-not-allowed"
                            : "bg-foreground hover:bg-foreground/90 text-background"
                        }`}
                      >
                        {downloading ? (
                          <>
                            <span className="animate-spin inline-block w-4 h-4 border-2 border-current border-t-transparent rounded-full" />
                            <span>{serverRunning ? "Downloading Real Media..." : "Compiling Playable Track..."}</span>
                          </>
                        ) : (
                          <>
                            <Download className="h-4 w-4" />
                            <span>
                              Download {serverRunning ? "Real" : "Track"} ({selectedFormat.type.toUpperCase()} - {selectedFormat.quality})
                            </span>
                          </>
                        )}
                      </button>

                      {!serverRunning && (
                        <div className="flex items-start gap-2.5 p-3 rounded border border-blue-500/20 bg-blue-950/20 text-blue-500 text-xs animate-in fade-in duration-200">
                          <Info className="h-4 w-4 shrink-0 mt-0.5" />
                          <div className="leading-relaxed">
                            <span className="font-bold">Static Mode:</span> You are downloading a valid, playable silent demo track. To download the real YouTube file, run <code className="font-mono bg-zinc-800 text-white px-1.5 py-0.5 rounded">npm run dev</code> locally to enable the backend extraction service.
                          </div>
                        </div>
                      )}
                    </div>

                    {downloadStatus && (
                      <div className="p-3.5 rounded bg-zinc-100 dark:bg-zinc-900 border border-border font-mono text-[10px] text-zinc-650 dark:text-zinc-400 leading-normal animate-in fade-in slide-in-from-bottom-2 duration-200">
                        <span className="text-emerald-500 dark:text-emerald-400 font-bold">$</span> {downloadStatus}
                      </div>
                    )}

                    {/* Local NPM Script command */}
                    <div className="space-y-2 border border-border/80 bg-zinc-50/50 dark:bg-zinc-950/20 rounded-lg p-3.5">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-1.5">
                          <Terminal className="h-3.5 w-3.5 text-muted" />
                          <span className="text-[11px] font-bold text-zinc-700 dark:text-zinc-300 uppercase tracking-wider">
                            Local NPM Project Command
                          </span>
                        </div>
                        <button
                          onClick={() => handleCopyCommand("npm")}
                          className="text-[10px] font-semibold flex items-center gap-1 bg-background hover:bg-muted/10 text-foreground transition-all py-1 px-2 rounded cursor-pointer border border-border"
                        >
                          {copiedText === "npm-cmd" ? (
                            <>
                              <Check className="h-3 w-3 text-emerald-500" />
                              <span className="text-emerald-500 font-semibold">Copied</span>
                            </>
                          ) : (
                            <>
                              <Copy className="h-3 w-3" />
                              <span>Copy NPM</span>
                            </>
                          )}
                        </button>
                      </div>
                      <div className="bg-zinc-900 text-zinc-100 font-mono text-[10px] p-2.5 rounded border border-zinc-800 overflow-x-auto break-all select-all">
                        {getCliCommand("npm")}
                      </div>
                      <p className="text-[9px] text-muted">
                        Paste and run this directly in your project root terminal. It runs our helper script using the local yt-dlp binary.
                      </p>
                    </div>

                    {/* Raw yt-dlp command */}
                    <div className="space-y-2 border border-border/80 bg-zinc-50/50 dark:bg-zinc-950/20 rounded-lg p-3.5">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-1.5">
                          <Terminal className="h-3.5 w-3.5 text-muted" />
                          <span className="text-[11px] font-bold text-zinc-700 dark:text-zinc-300 uppercase tracking-wider">
                            Raw yt-dlp Command
                          </span>
                        </div>
                        <button
                          onClick={() => handleCopyCommand("raw")}
                          className="text-[10px] font-semibold flex items-center gap-1 bg-background hover:bg-muted/10 text-foreground transition-all py-1 px-2 rounded cursor-pointer border border-border"
                        >
                          {copiedCommand ? (
                            <>
                              <Check className="h-3 w-3 text-emerald-500" />
                              <span className="text-emerald-500 font-semibold">Copied</span>
                            </>
                          ) : (
                            <>
                              <Copy className="h-3 w-3" />
                              <span>Copy Command</span>
                            </>
                          )}
                        </button>
                      </div>
                      <div className="bg-zinc-900 text-zinc-100 font-mono text-[10px] p-2.5 rounded border border-zinc-800 overflow-x-auto break-all select-all">
                        {getCliCommand("raw")}
                      </div>
                      <div className="flex items-start gap-1.5 text-[9px] text-muted">
                        <Info className="h-3 w-3 shrink-0 mt-0.5" />
                        <span>
                          Alternative raw command using global <code className="font-mono text-foreground font-semibold">yt-dlp</code> installation.
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
      {/* FAQ Section */}
      <div className="border-t border-border pt-10 mt-8">
        <FAQAccordion items={YOUTUBE_FAQS} idPrefix="youtube-faq" />
      </div>
    </div>
  );
}
